### ISSUE TITLE
How to get human readable incoming message.

### ISSUE THREAD

**Issue by manti-by** [drslump/Protobuf-PHP#13]
Hi. I reviewed all code from your library but not found how to get incoming message in human readable view.
I found method encode, but I don't know what kind of object I need to put into this method.
Maybe you know the best way to do this. What method can I use after "$request->parse($this->_request_string)" to get usual string for binary representation of "$this->_request_string".

**Comment by drslump** [comment]
The library is modeled around the `codec` concept for parsing and serializing messages. Here is an example on how to use the `TextFormat` one. If you prefer Json or XML there are also codecs available for them.

```
$text_codec = new \DrSlump\Protobuf\Codec\TextFormat();
echo $text_codec->encode($request)
```
