### ISSUE TITLE
"File does not reside within path"

### ISSUE THREAD

**Issue by nabeelio** [drslump/Protobuf-PHP#14]
I'm not quite understanding this error:

``` bash
$ protoc-gen-php -o ./php MsgMgtPing.proto 
Protobuf-PHP 0.9.4 by Ivan -DrSlump- Montes

/var/.../.../../message/MsgMgtPing.proto: File does not reside within any 
path specified using --proto_path (or -I).  You must specify a --proto_path 
which encompasses this file.  Note that the proto_path must be an exact 
prefix of the .proto file names -- protoc is too dumb to figure out when two 
paths (e.g. absolute and relative) are equivalent (it's harder than you think).

ERROR: protoc exited with an error (1) when executed with: 
  protoc \
    --plugin=protoc-gen-php='/usr/bin/protoc-gen-php' \
    --proto_path='/usr/share/php/DrSlump/Protobuf/Compiler/protos' \
    --php_out=':./php' \
    '/var/.../.../.../message/MsgMgtPing.proto'

```

``` bash
$ protoc --version
libprotoc 2.4.1
```

**Comment by nabeelio** [comment]
Cleaning this up also gives the same message:

``` bash
$ protoc --plugin=protoc-gen-php='/usr/bin/protoc-gen-php' \
     --proto_path='/usr/share/php/DrSlump/Protobuf/Compiler/protos' \
     --php_out='./php' MsgMgtPing.proto 

/opt/.../.../message/MsgMgtPing.proto: File does not reside within any path 
specified using --proto_path (or -I).  You must specify a --proto_path which 
encompasses this file.  Note that the proto_path must be an exact prefix 
of the .proto file names -- protoc is too dumb to figure out when two 
paths (e.g. absolute and relative) are equivalent (it's harder than you think).
```

Same if I use an absolute path to the .proto file, as well as include an additional `proto_path=` containing the path to the file

**Comment by drslump** [comment]
Google's protoc compiler complains that it can't resolve where the `MsgMgtPing.proto` from its list of include paths. Try adding `--proto_path=.` to add the current directory as include path.  If using `protoc-gen-php`, try with `protoc-gen-php -o ./php -i . MsgMgtPing.proto`

**Comment by nalagg** [comment]
im getting:
PHP Warning:  Module 'dom' already loaded in Unknown on line 0
Protobuf-PHP 0.9.4 by Ivan -DrSlump- Montes

PHP Warning:  Module 'dom' already loaded in Unknown on line 0
./php/: No such file or directory

ERROR: protoc exited with an error (1) when executed with:
  protoc \
    --plugin=protoc-gen-php='/usr/bin/protoc-gen-php' \
    --proto_path='/usr/share/pear/DrSlump/Protobuf/Compiler/protos' \
    --proto_path='/var/www/path/to/googleProtoBuf' \
    --php_out=':./php' \
    '/var/www/path/to/googleProtoBuf/addressbook.proto'

**Comment by cmzz** [comment]
Thanks. Its help for me.

**Comment by yangyf1990** [comment]
@cmzz how do you solve it ?
