### ISSUE TITLE
Empty repeated messages are not parsed correctly

### ISSUE THREAD

**Issue by cavedon** [drslump/Protobuf-PHP#17]
A message containing an empty repeated messages breaks parsing. See examples below

```
// test.proto
package test;
message Inner {
    optional int32 inner_value = 1;
}

message Outer {
    repeated Inner inner = 1;
    optional int32 outer_value = 2;
} 
```

and

```
// create_dump_test.py 
#!/usr/bin/env python

import test_pb2

# Create PB

outer = test_pb2.Outer()
outer.inner.add()
outer.outer_value = 1

s = outer.SerializeToString()
with open('test.pb', 'w') as f:
    f.write(s)

# Load and dump PB

outer = test_pb2.Outer()

with open('test.pb', 'r') as f:
    outer.ParseFromString(f.read())

print outer
```

Will give you:

```
inner {
}
outer_value: 1
```

If you parse it with Protobuf-PHP it will try to decode outer_value as member of the Inner message, instead of Outer, therefore failing to parse the rest of the message.

The following php code

```
use \DrSlump\Protobuf;
Protobuf::autoload();
require_once('test.php');

$fp = fopen("test.pb", 'r');
$pb_data = fread($fp, 1024);
fclose($fp);

$pb = new test\Outer();
$pb->parse($pb_data);

$codec = new \DrSlump\Protobuf\Codec\TextFormat();

print($codec->encode($pb)."\n");
```

Will give you :

```
inner {
}
```

(i.e. missing outer_value: 1)

**Comment by drslump** [comment]
Thanks @cavedon! 

I actually found this bug some time ago but only fixed it on the lazy branch (my mistake). To me it is a bug in the encoding library, a zero-length nested message should be completely omitted from the encoded stream, but since some libraries seem to work that way is obviously needed to play safe with it :)

**Comment by cavedon** [comment]
Thanks for the quick feedback.
I do not agree it is an encoding error: it might be relevant  whether a repeated filed is present or not. The message of the field, however, can be empty meaning that the optional fields take the default values.
