### ISSUE TITLE
inner extend not worked

### ISSUE THREAD

**Issue by bookvik** [drslump/Protobuf-PHP#19]
PHP version not fill extensions list.

https://gist.github.com/3742079

**Comment by drslump** [comment]
Could you provide the .proto file too, please?

**Comment by bookvik** [comment]
``` protobuf
message A {
  optional string first = 1;
  extensions 2 to 3;
}

message B {
  extend A {
    optional string second = 2;
  }
}
```

**Comment by drslump** [comment]
Thanks for the report @bookvik!

A simple usage example can be seen at https://github.com/drslump/Protobuf-PHP/blob/master/tests/Protobuf.Codec.Binary.spec.php#L204
