### ISSUE TITLE
Generating php classes script error

### ISSUE THREAD

**Issue by acwind** [drslump/Protobuf-PHP#20]
When Generating PHP classes, it report error:

File does not reside within any path specified using --proto_path (or -I).  You must specify a --proto_path which encompasses this file.  Note that the proto_path must be an exact prefix of the .proto file names -- protoc is too dumb to figure out when two paths (e.g. absolute and relative) are equivalent (it's harder than you think).

ERROR: protoc exited with an error (1) when executed with: 
  protoc \
    --plugin=protoc-gen-php='/Users/myproject/libs/Protobuf-PHP/protoc-gen-php.php' \
    --proto_path='/myproject/libs/Protobuf-PHP/library/DrSlump/Protobuf/Compiler/protos' \
    --php_out=':./' \
    '/myproject/test.proto'

**Comment by acwind** [comment]
forget import "php.proto"

**Comment by nalagg** [comment]
im getting the same error,  what do you mean forget import "php.proto"?
