### ISSUE TITLE
protoc-gen-php is not found when protoc is run from the command line

### ISSUE THREAD

**Issue by nalagg** [drslump/Protobuf-PHP#22]
protoc --plugin=protoc-gen-php --php_out=./build simple.proto

error message:
protoc-gen-php: program not found or is not executable
--php_out: protoc-gen-php: Plugin failed with status code 1.

fixed: protoc --plugin=/FULL/PATH/TO/protoc-gen-php --php_out=./build simple.proto

**Comment by andruwik777** [comment]
Thanks! It helps me!
