### ISSUE TITLE
Read the contents of a protocol buffer

### ISSUE THREAD

**Issue by dimxasnewfrozen** [drslump/Protobuf-PHP#30]
I have a socket that returns a protocol buffer. When I try and read it, I see it as array but with junk for data (binary I'm assuming). 

How can I un-serialize this data? Currently I'm trying:

$codec= new \DrSlump\Protobuf\Codec\PhpArray();
echo $codec->encode($response);

$response is not an instance of DrSlump\Protobuf\message - obviously...

Note: I can send the protocol buffer TO the socket fine - I'm just trying to read the response back.

**Comment by drslump** [comment]
I assume that the data you're retrieving is encoded in the standard binary protobuf format, if so, you could try something like this:

```
$codec = new \DrSlump\Protobuf\Codec\Binary();
$myObject = $codec->decode(new \MyProtos\MyObject(), $response);

//  or just simply use the default interface to the binary codec

$myObject = \DrSlump\Protobuf::decode('\MyProtos\MyObject', $response);
```

Note that protobuf messages are not self-descriptive, so it's not possible to find out what message they represent from the data in the wire, we always have to indicate the message descriptor when decoding (`MyObject` in the example above).

The alternative codecs like `PhpArray` or `Json` are useful when you want to use the `.proto` files to define your messages but are not communicating with a standard protobuf client/server, we use them for example to dump request logs in a human-readable format. To be 100% compatible you need to use the Binary codec, which is the one understood by other protobuf implementations.
