### ISSUE TITLE
can't find Console/CommandLine.php why?

### ISSUE THREAD

**Issue by xiefei** [drslump/Protobuf-PHP#31]
PHP Warning:  require_once(Console/CommandLine.php): failed to open stream: No such file or directory in /Users/Qing/code/gitcode/Protobuf-PHP/library/DrSlump/Protobuf/Compiler/Cli.php on line 5

Warning: require_once(Console/CommandLine.php): failed to open stream: No such file or directory in /Users/Qing/code/gitcode/Protobuf-PHP/library/DrSlump/Protobuf/Compiler/Cli.php on line 5

**Comment by drslump** [comment]
If you don't install the package with `pear` you need to install the dependency manually:

```
pear install Console_CommandLine
```
