### ISSUE TITLE
pear.pollinimini.net is down

### ISSUE THREAD

**Issue by vortechs2000** [drslump/Protobuf-PHP#43]
Looks like pear.pollinimini.net is down.  I'm not able to access it to install the Protobuf-PHP package.

**Comment by drslump** [comment]
should be fixed now, thanks!

**Comment by vortechs2000** [comment]
Thank you!

**Comment by WindWood** [comment]
Does the pear.pollinimini.net down again?

**Comment by drslump** [comment]
fixed. Sorry, the web server was down, will investigate with the provider what went on. Thanks!

**Comment by Aravinthvvs** [comment]
:( 
Again pollinimini.net is down

**Comment by Aravinthvvs** [comment]
Again pollinimini.net is down

**Comment by microidea** [comment]
Looks like pollinimini.net is down again, so unstable...
