### ISSUE TITLE
Fatal error: Class 'DrSlump\Protobuf\Message' not found

### ISSUE THREAD

**Issue by manti-by** [drslump/Protobuf-PHP#6]
I used several ways to include Protobuf libraries (directly and over PEAR), but I can't resolve this issue.
Can you provide more detailed instructions how to use your libraries.

P.S. I used last code from github, compile my class from this proto https://code.google.com/apis/adx-rtb/docs/supporting/realtime-bidding-proto.txt and try to run my script, but...

**Comment by drslump** [comment]
Sorry, you're right, I didn't document how to setup the autoloader for the library files. You should use something like this:

``` php
require_once 'DrSlump/Protobuf.php';

// Register the library autoloader so that you don't need to handle it yourself
\DrSlump\Protobuf::autoload();
```

There is a huge refactor coming up in the `lazy` branch which improves greatly the performance, including a C extension for decoding, and will also register the autoloader automatically to avoid this kind of confusions.
