### ISSUE TITLE
Expected wire type 2 but got 1 for type 11

### ISSUE THREAD

**Issue by manti-by** [drslump/Protobuf-PHP#7]
Hi. Also one new question.

I tryed to decode request (see example bellow) but in any way I have these message
`Uncaught exception 'RuntimeException' with message 'Expected wire type 2 but got 1 for type 11'`
where type 11 is "url" field in request. 

**Request example**

id: "Mv\2005\000\017.\001\n\345\177\307X\200M8"
ip: "\314j\310\004"
user_agent: "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/534.13 (KHTML, like Gecko) Chrome/9.0.597.107 Safari/534.13,gzip"
country: "US"
region: "US-MA"
city: "Boston"
metro: 506
url: "http://www.example.com/"
detected_language: "en"

**Code example**

require_once 'class/DrSlump/Protobuf.php';
\DrSlump\Protobuf::autoload();

include_once 'class/AdX.php';
$request = new BidRequest();

$data = file_get_contents('php://input');
$request->parse($data);

_P.S. For the next time can I'll ask my questions here?_

**Comment by drslump** [comment]
I would need to have a look at your .proto file so I can try to reproduce the problem. How are you generating the encoded data in the first place?

Feel free to post your questions here or mail me (drslump at pollinimini.net) if the question contains sensitive information.

**Comment by manti-by** [comment]
I generate PHP class from these proto https://code.google.com/apis/adx-rtb/docs/supporting/realtime-bidding-proto.txt by protoc compiler with you tool **protoc-gen-php** (Ubuntu, PHP 5.3.8) and try to parse example request from https://code.google.com/apis/adx-rtb/docs/request.html#example-bid-request.

The generated php file here http://marco-manti.jino.ru/files/AdX.zip

**Comment by drslump** [comment]
I guess the problem is that you're feeding the data in TextFormat which parsing is not supported by the library. You can convert the example given the documentation to the binary format with the following command:

```
cat sample.txt | protoc --encode=BidRequest sample.proto > sample.bin
```

Now you can feed the sample.bin to your php script.

Protobuf-PHP supports TextFormat only when serializing (encoding) but it doesn't support its deserialization (decoding).

**Comment by manti-by** [comment]
Thank you very much! All works fine (for now).

_P.S. And I found a small bug in your code http://pix.am/k4A6/._

**Comment by drslump** [comment]
Thanks, I've fixed the bug with the call to getWireType without the second parameter
